spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql:
      true

  datasource:
    url:
      jdbc:mysql://hostpitalchanneling.mysql.database.azure.com:3306/hospital_management_system?useSSL=true&serverTimezone=UTC&failOverReadOnly=false&createDatabaseIfNotExist=true
    username:
      HCSadmin
    password:

    driver-class-name:
      com.mysql.cj.jdbc.Driver
